# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('solution_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=30)),
                ('study_group', models.ManyToManyField(to='cuotiben.StudyGroup')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='people',
            field=models.ManyToManyField(to='cuotiben.User'),
        ),
        migrations.AddField(
            model_name='problem',
            name='study_group',
            field=models.ManyToManyField(to='cuotiben.StudyGroup'),
        ),
    ]
